package com.a0.daleelak.ui

import android.content.Context
import android.content.res.Configuration
import androidx.compose.runtime.staticCompositionLocalOf
import com.a0.daleelak.R
import java.util.Locale

/** Only app-owned labels are translated. Conversations and government source text retain their language. */
class UiStrings(context: Context, val english: Boolean) {
    private val localized = context.createConfigurationContext(Configuration(context.resources.configuration).apply {
        setLocale(Locale.forLanguageTag(if (english) "en" else "ar"))
    })
    fun text(arabic: String): String = labels[arabic]?.let { localized.getString(it) } ?: arabic
    fun choose(arabic: String, english: String): String = if (this.english) english else arabic
    companion object {
        private val labels = mapOf(
        "دليلك" to R.string.ui_0,
        "DALEELAK · نسخة تجريبية" to R.string.ui_1,
        "الرئيسية" to R.string.ui_2,
        "إغلاق" to R.string.ui_3,
        "شو بدك تنجز اليوم؟" to R.string.ui_4,
        "ابدأ معاملة جديدة، أو كمل من وين وقفت." to R.string.ui_5,
        "معاملة جديدة" to R.string.ui_6,
        "معاملاتك" to R.string.ui_7,
        "المعاملات الحالية" to R.string.ui_8,
        "الجديدة والجارية" to R.string.ui_9,
        "المعاملات المنتهية" to R.string.ui_10,
        "اللي أكملت متابعتها" to R.string.ui_11,
        "أرشيف المعاملات" to R.string.ui_12,
        "معاملاتك المؤرشفة" to R.string.ui_13,
        "جديدة" to R.string.ui_14,
        "جارية" to R.string.ui_15,
        "مكتملة" to R.string.ui_16,
        "الكل" to R.string.ui_17,
        "الحالية" to R.string.ui_18,
        "المنتهية" to R.string.ui_19,
        "الأرشيف" to R.string.ui_20,
        "معاملاتي" to R.string.ui_21,
        "ما عندك معاملات محفوظة بعد. ابدأ معاملة جديدة من الرئيسية." to R.string.ui_22,
        "ما عندك معاملات حالية." to R.string.ui_23,
        "ما عندك معاملات منتهية بعد." to R.string.ui_24,
        "ما عندك معاملات مؤرشفة بعد." to R.string.ui_25,
        "مؤرشفة · " to R.string.ui_26,
        " · تقدم أبلغ عنه المستخدم" to R.string.ui_27,
        "عرض" to R.string.ui_28,
        "متابعة" to R.string.ui_29,
        "المساعد" to R.string.ui_30,
        "كتم" to R.string.ui_31,
        "صوت" to R.string.ui_32,
        "محادثة جديدة" to R.string.ui_33,
        "أنت" to R.string.ui_34,
        "دليلك · تجربة" to R.string.ui_35,
        "إلغاء تجهيز الصوت" to R.string.ui_36,
        "إيقاف" to R.string.ui_37,
        "استماع" to R.string.ui_38,
        "جارٍ تجهيز الرد…" to R.string.ui_39,
        "نموذج عرض للخطة؛ ليس إجراءً حكومياً موثقاً." to R.string.ui_40,
        "تفاصيل تحتاج تأكيد" to R.string.ui_41,
        "حفظ الخطة ومتابعة الخطوات" to R.string.ui_42,
        "اكتب أو عدّل رسالتك" to R.string.ui_43,
        "جارٍ تفريغ الصوت…" to R.string.ui_44,
        "إنهاء التسجيل" to R.string.ui_45,
        "إنهاء الإملاء" to R.string.ui_46,
        "احكي لدليلك" to R.string.ui_47,
        "إخفاء" to R.string.ui_48,
        "كتابة" to R.string.ui_49,
        "إرسال" to R.string.ui_50,
        "سجّل حتى ٣٠ ثانية. يُرسل النص تلقائياً بعد تفريغ الصوت. صوت الرد مولّد آلياً." to R.string.ui_51,
        "خدمة الصوت غير متاحة في هذه النسخة، اكتب رسالتك." to R.string.ui_52,
        "يُرسل النص تلقائياً عند انتهاء الإملاء. قد يعالج جهازك الصوت عبر خدمة التعرف." to R.string.ui_53,
        "لم يُسمح باستخدام الميكروفون. تقدر تكتب رسالتك بدلاً من ذلك." to R.string.ui_54,
        "ما وصلني كلام واضح. جرّب مرة ثانية أو اكتب رسالتك." to R.string.ui_55,
        "يلزم السماح بالميكروفون للإملاء الصوتي." to R.string.ui_56,
        "تعذر الاتصال بخدمة التعرف الصوتي. تقدر تكتب رسالتك." to R.string.ui_57,
        "تعذر تشغيل الإملاء الصوتي؛ تقدر تكتب رسالتك." to R.string.ui_58,
        "خدمة التعرف الصوتي غير متاحة على هذا الجهاز. تقدر تكتب رسالتك." to R.string.ui_59,
        "تعذر بدء الإملاء الصوتي؛ تقدر تكتب رسالتك." to R.string.ui_60,
        "رجوع للمعاملات" to R.string.ui_61,
        "خطة تجريبية · التقدم حسب تأكيدك" to R.string.ui_62,
        "التقدم حسب تأكيدك" to R.string.ui_63,
        "شو أعمل الآن؟" to R.string.ui_64,
        "نظرة عامة" to R.string.ui_65,
        "متابعة المعاملة" to R.string.ui_66,
        "إنهاء" to R.string.ui_67,
        "اللي تقدر تتابعه الآن" to R.string.ui_68,
        "هاي المهام متاحة بنفس الوقت. شوفها مع بعض قبل ما ترتّب مشوارك." to R.string.ui_69,
        "شوف الخطوة المتاحة ومتطلباتها قبل ما تبدأ." to R.string.ui_70,
        "راجعت كل الخطوات. تقدر تؤكد اكتمال المتابعة من البطاقة الأخيرة." to R.string.ui_71,
        "ما في خطوة متاحة الآن. راجع الخطوات السابقة قبل المتابعة." to R.string.ui_72,
        "تفاصيل الخطوة" to R.string.ui_73,
        "اسحب للأعلى عشان تشوف الخطوات القادمة. عرضها ما يعني إنها جاهزة للتنفيذ." to R.string.ui_74,
        "حجز موعد · محاكاة" to R.string.ui_75,
        "محاكاة محلية، لا تنشئ موعداً رسمياً ولا تعني أن الخدمة تتطلب حجزاً." to R.string.ui_76,
        "إعادة فتح المعاملة" to R.string.ui_77,
        "أؤكد اكتمال المتابعة" to R.string.ui_78,
        "تأكيدك محلي، ولا يمثل موافقة أو حالة حكومية رسمية." to R.string.ui_79,
        "استعادة من الأرشيف" to R.string.ui_80,
        "أرشفة المعاملة" to R.string.ui_81,
        "أكملتها حسب تأكيدك" to R.string.ui_82,
        "متاحة للمتابعة" to R.string.ui_83,
        "خطوة قادمة · تقدر تشوف متطلباتها الآن" to R.string.ui_84,
        "المتطلبات الموثقة لسه مش مضافة للخطة التجريبية." to R.string.ui_85,
        "لا توجد متطلبات إضافية مذكورة في هذه الخطوة." to R.string.ui_86,
        "مصادر الخطوة" to R.string.ui_87,
        "إعادة فتح الخطوة" to R.string.ui_88,
        "أؤكد إكمال الخطوة" to R.string.ui_89,
        "تأكيد هذه الخطوة يعلّم كل الخطوات السابقة كمكتملة أيضاً." to R.string.ui_90,
        "السابق" to R.string.ui_91,
        "التالي" to R.string.ui_92,
        "أرشفة المعاملة؟" to R.string.ui_93,
        "ستنتقل إلى الأرشيف مع حفظ المحادثة والخطوات والتقدم. يمكنك استعادتها لاحقاً." to R.string.ui_94,
        "أرشفة" to R.string.ui_95,
        "إلغاء" to R.string.ui_96,
        "مطلوب" to R.string.ui_97,
        "مفيد للتحضير" to R.string.ui_98,
        "مطلوب حسب الحالة" to R.string.ui_99,
        "الوثائق" to R.string.ui_100,
        "الإجراءات" to R.string.ui_101,
        "الدفعات والالتزامات" to R.string.ui_102,
        "الزيارات" to R.string.ui_103,
        "الأصل" to R.string.ui_104,
        "نسخة ورقية" to R.string.ui_105,
        "رفع إلكتروني" to R.string.ui_106,
        "سجل إلكتروني رسمي" to R.string.ui_107,
        "تعذر فتح قائمة المصادر المراجعة المحلية؛ لا نعرض تفاصيل غير مؤكدة." to R.string.ui_108,
        "لا يتوفر رابط رسمي مذكور لهذا المصدر في الملفات المراجعة." to R.string.ui_109,
        "فتح المصدر الرسمي" to R.string.ui_110,
        "لم نتمكن من فتح الرابط في تطبيق على هذا الجهاز." to R.string.ui_111,
        "أهلاً! احكيلي عن المشكلة أو المعاملة اللي بدك مساعدة فيها. رح أستخدم المعلومات الموثقة المتاحة." to R.string.ui_112,
        "احكيلي عن المشكلة أو المعاملة اللي بدك مساعدة فيها." to R.string.ui_113,
        "تعذر قراءة المحفوظات. لم نحذفها؛ الحفظ معطل لمنع استبدال بيانات غير مقروءة." to R.string.ui_114,
        "عاد المساعد للوضع المحلي المحدود." to R.string.ui_115,
        "تم تفعيل فهم الرسائل عبر OpenRouter لهذه الجلسة فقط؛ لا يُحفظ المفتاح." to R.string.ui_116,
        "اسم الصوت غير صالح. استخدم اسماً أو معرّفاً من ElevenLabs." to R.string.ui_117,
        "ما وصلني كلام واضح. لم نرسل التسجيل؛ جرّب مرة ثانية أو اكتب رسالتك." to R.string.ui_118,
        "تعذر الإملاء. بقي نصك؛ تقدر تكتب رسالتك." to R.string.ui_119,
        "تعذر تفريغ التسجيل؛ بقي النص." to R.string.ui_120,
        "فعّل مفتاح OpenRouter للاستماع للرد." to R.string.ui_121,
        "تعذر الاستماع؛ الرد المكتوب متاح." to R.string.ui_122,
        "جارٍ تحميل المحفوظات، حاول بعد لحظة." to R.string.ui_123,
        "تعذر قبول الرد. بقيت رسالتك والخطة السابقة؛ حاول مجدداً. هذا خطأ استجابة وليس خدمة غير مدعومة." to R.string.ui_124,
        "لا توجد خطة مقبولة للحفظ بعد." to R.string.ui_125,
        "راجع كل الخطوات أولاً." to R.string.ui_126,
        "اكتملت متابعة الجزء المحفوظ حسب تأكيدك فقط؛ ليست موافقة حكومية أو إثبات اكتمال الإجراء الكامل." to R.string.ui_127,
        "حجز تجريبي محلي فقط. لم يُنشأ موعد رسمي ولا يدل على توافر أو اشتراط الحجز." to R.string.ui_128,
        "تغيرت إجابة أو مهمة تؤثر على التقدم؛ أُعيد فتح الجزء المتأثر فقط وبقي العمل غير المتأثر محفوظاً." to R.string.ui_129,
        "الحفظ غير متاح حتى تُقرأ البيانات المحلية بنجاح." to R.string.ui_130,
        "فشل الحفظ؛ بقيت الخطة والمحادثة ظاهرتين والبيانات المحفوظة السابقة محفوظة." to R.string.ui_131,
        "تم استئناف المعاملة المحفوظة. يمكن تصحيح إجاباتها دون حذف التقدم غير المتأثر." to R.string.ui_132,
        "الخطة المحفوظة معروضة كما كانت؛ سياق الرد يحتاج مراجعة قبل استخدامه." to R.string.ui_133,
        "تعذر حفظ سياق المحادثة؛ المعاملات المحفوظة لم تُحذف." to R.string.ui_134,
        )
    }
}
val LocalUiStrings = staticCompositionLocalOf<UiStrings> { error("UI strings provider missing") }
